version: '3.8'

services:
  playground_service:
    container_name: playground_service
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${APP_PORT}:3000
    env_file:
      - ./.env
