apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Release.Namespace }}

spec:
  ingressClassName: nginx
  rules:
  - host: exec.yds.cuterabbit.art
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "exec-nginx-proxy.fullname" . }}
            port:
              number: 80
  tls:
    - hosts:
        - exec.yds.cuterabbit.art