apiVersion: v1
kind: Service
metadata:
  name: {{ include "exec-nginx-proxy.fullname" . }}
  labels:
    {{- include "exec-nginx-proxy.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    {{- include "exec-nginx-proxy.selectorLabels" . | nindent 4 }}
