apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccount.name }}
  name: {{ .Chart.Name }}-token-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/service-account-token