export const BeaconEvent = {
    LIST_DIR: 'LIST_DIR',
    DIR_TREE: 'DIR_TREE',
    DIR_FLAT_TREE: 'DIR_FLAT_TREE',
    FILE_PROPERTIES: 'FILE_PROPERTIES',
    GET_FILE_CONTENT: 'GET_FILE_CONTENT',
    CREATE_FILE: 'CREATE_FILE',
    CREATE_FOLDER: 'CREATE_FOLDER',
    RENAME: 'RENAME',
    DELETE: 'DELETE',
    SAVE_FILE_CONTENT: 'SAVE_FILE_CONTENT',
};
