export const LighthouseEvent = {
    HEARTBEAT: 'HEARTBEAT',
    REQUEST_VM_FOR_WORKSPACE: 'REQUEST_VM_FOR_WORKSPACE',
    REQUEST_EXEC_URL: 'REQUEST_EXEC_URL',
    REQUEST_ATTACH_URL: 'REQUEST_ATTACH_URL',
    GET_LIST_PORT_FORWARD: 'GET_LIST_PORT_FORWARD',
    REQUEST_PORT_FORWARD: 'REQUEST_PORT_FORWARD',
    DELETE_PORT_FORWARD: 'DELETE_PORT_FORWARD',
};
