export const LighthouseEvent = {
    HEARTBEAT: 'HEARTBEAT',
    REQUEST_VM_FOR_WORKSPACE: 'REQUEST_VM_FOR_WORKSPACE',
    REQUEST_EXEC_URL: 'REQUEST_EXEC_URL',
    REQUEST_ATTACH_URL: 'REQUEST_ATTACH_URL',
};
