apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "beacon.fullname" . }}-pvc-beacon
spec:
  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 1Gi

  storageClassName: nfs-csi