apiVersion: management.cattle.io/v3
kind: Project
metadata:
  annotations:
    authz.management.cattle.io/creator-role-bindings: '{"created":["project-owner"],"required":["project-owner"]}'
    lifecycle.cattle.io/create.mgmt-project-rbac-remove: 'true'
    lifecycle.cattle.io/create.project-namespace-auth_local: 'true'
  finalizers:
    - controller.cattle.io/mgmt-project-rbac-remove
    - clusterscoped.controller.cattle.io/project-namespace-auth_local
  generateName: p-
  labels:
    cattle.io/creator: norman
  name: p-guest-vm
  namespace: local
spec:
  clusterName: local
  containerDefaultResourceLimit: {}
  description: VM for Guest
  displayName: GuestVM
  enableProjectMonitoring: false
  namespaceDefaultResourceQuota:
    limit: {}
  resourceQuota:
    limit: {}
    usedLimit: {}