keycloak:
  image:
    registry: ghcr.io
    repository: phuchptty/yggdrasil/keycloak
    tag: latest
    pullPolicy: Always

  production: true
  proxy: edge
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      cert-manager.io/cluster-issuer: le-dns01
      nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    hostname: auth.yds.cuterabbit.art
    tls: true
  auth:
    adminUser: admin
    adminPassword: HH223344!@#
  resources:
    limits:
      cpu: "2000m"
      memory: "2Gi"
    requests:
      cpu: "300m"
      memory: "1Gi"
  postgresql:
    auth:
      postgresPassword: 9RmmLUI2FX
      password: 9vQJSG8iWQ