keycloak:
  image:
    registry: ghcr.io
    repository: phuchptty/yggdrasil/keycloak
    tag: latest
    pullPolicy: Always

  production: true

  proxy: edge

  extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_FRONTEND_URL
      value: https://auth.yds.cuterabbit.art

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: le-dns01
      nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    hostname: auth.yds.cuterabbit.art
    tls: true

  auth:
    adminUser: admin
    adminPassword: HH223344!@#

  resources:
    limits:
      cpu: "2000m"
      memory: "2Gi"
    requests:
      cpu: "300m"
      memory: "1Gi"

  postgresql:
    auth:
      postgresPassword: 9RmmLUI2FX
      password: 9vQJSG8iWQ