export const VM_MANAGER_QUEUE_NAME = "vm-manager";

export const VmManagerEvent = {
    CONNECTION_MESSAGE: "CONNECTION_MESSAGE",
    REQUEST_VM_FOR_WORKSPACE: "REQUEST_VM_FOR_WORKSPACE",
    HEARTBEAT: "HEARTBEAT",
    REQUEST_EXEC_URL: "REQUEST_EXEC_URL",
    REQUEST_ATTACH_URL: "REQUEST_ATTACH_URL",
    REQUEST_PORT_FORWARD: "REQUEST_PORT_FORWARD",
    GET_LIST_PORT_FORWARD: "GET_LIST_PORT_FORWARD",
};

export enum VmState {
    PROVISIONED = "PROVISIONED",
    DISCONNECTED = "DISCONNECTED",
    PENDING_DELETE = "PENDING_DELETE",
}
