apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-dns01
  namespace: cert-manager
spec:
  acme:
    email: cm-yggdrasil@nicetoo.cyou
    preferredChain: ""
    privateKeySecretRef:
      name: le-dns01-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
