apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-http01
  namespace: cert-manager
spec:
  acme:
    email: cm-yggdrasil@nicetoo.cyou
    preferredChain: ""
    privateKeySecretRef:
      name: le-http01-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
