ingress:
  controller:
    ingressClass: "nginx"
    ingressClassResource:
      controllerValue: "k8s.io/ingress-nginx"
      default: true
      name: "nginx"
    podLabels:
      sidecar.istio.io/inject: "true"
      app: "ingress-nginx"
      version: "1"
    config:
      use-forwarded-headers: "true"
      enable-brotli: "true"
      service-upstream: "true"
    extraArgs:
      default-ssl-certificate: ingress-nginx/ingress-default-certificate-tls

defaultCertificate:
  dnsNames:
    - "*.cuterabbit.art"
  issuerRef:
    kind: ClusterIssuer
    name: le-dns01
