export const errorMessageConstant = {
    MISSING_AUTHORIZATION_HEADER: "MISSING_AUTHORIZATION_HEADER",
    INVALID_TOKEN: "INVALID_TOKEN",
    NO_WORKSPACE_FOUND_OR_USER_NO_PERMISSION: "NO_WORKSPACE_FOUND_OR_USER_NO_PERMISSION",
    ONLY_ONE_VM_PER_WORKSPACE: "ONLY_ONE_VM_PER_WORKSPACE",
    VM_NOT_FOUND: "VM_NOT_FOUND",
    VM_DELETED_FOR_TIMEOUT: "VM_DELETED_FOR_TIMEOUT",
};
