version: "3.8"

services:
  db:
    image: bitnami/postgresql:15
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_DATABASE=keycloak
    volumes:
      - pgdata:/bitnami/postgresql

  keycloak:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=db
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=password
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_PRODUCTION=true
      - KEYCLOAK_PROXY=edge

volumes:
  pgdata: