apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-role-binding

subjects:
  - kind: ServiceAccount
    name: {{ include "lighthouse.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

roleRef:
  kind: ClusterRole
  name: lighthouse-cluster-role
  apiGroup: rbac.authorization.k8s.io
