name: Build Beacon Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - pkg/beacon/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/beacon

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${IMAGE_NAME,,}" >>${GITHUB_ENV}

      - name: Build Docker Image
        run: |
          cd pkg/beacon
          docker build -t ${{ env.REGISTRY }}/${{ env.OWNER_LC }} .

      - name: Push Docker Image
        run: docker push ${{ env.REGISTRY }}/${{ env.OWNER_LC }}:latest