name: Build Base Image C++

on:
  workflow_dispatch:
  push:
    paths:
      - infrastructures/docker/baseImages/cpp/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/base/cpp

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${IMAGE_NAME,,}" >>${GITHUB_ENV}

      - name: Build Docker Image
        run: |
          cd infrastructures/docker/baseImages/cpp
          docker build -t ${{ env.REGISTRY }}/${{ env.OWNER_LC }} .

      - name: Push Docker Image
        run: docker push ${{ env.REGISTRY }}/${{ env.OWNER_LC }}:latest